name: zam_firestore
version: 0.0.1
description: An adapter for the cloud_firestore plugin for flutter.
homepage: https://zamstation.com
repository: https://github.com/zamstation/zam_firestore
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  cloud_firestore: ^2.5.3
  flutter:
    sdk: flutter
  zam_database:
    git: git://github.com/zamstation/zam_database.git

dev_dependencies:
  lints: ^1.0.1
  zam_test: ^0.4.0
