name: zam_firestore
version: 0.1.0
description: An adapter for the cloud_firestore plugin for flutter.
homepage: https://zamstation.com
repository: https://github.com/zamstation/zam_firestore
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cloud_firestore: ^2.5.3
  flutter:
    sdk: flutter
  zam_database:
    git: https://github.com/zamstation/zam_database.git

dev_dependencies:
  lints: ^2.0.0
  zam_test: ^0.5.0
